### PR TITLE
Fix#16

### LINKED ISSUE #16: Rename filename config.js
**Describe the bug**
The filename `config.js` needs to be renamed as `standard` ignores it by default. Using `utils.js` looks a good option.

**Expected behavior**
`standard` should cover the entire codebase except defaults like `node_modules` etc

### PR DESCRIPTION
**Pull request by blogpranav**
### Description
Renaming the file config.js according to the standard. Changed the filename to util.js

Fixes #16 

### Type of Change:
Change in filename.

- [ ] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by rsarky** [comment]
LGTM, can you squash your commits and follow the Semantic Commit messages guidelines too?
You can read about `git rebase` to achieve thiss.
Tell me if you need help

**Comment by blogpranav** [comment]
Should I make another PR? Can you please elaborate a lil bit?

**Comment by rsarky** [comment]
Sure!
So normally we want to have one commit per feature. It keeps the git history clean.
So what we need to do is _squash_ the 3 commits that you have, into one.

Essentially you need to use the `git rebase` command to squash these commits. There are other ways but I find this the easiest.
So in your feature branch you can run `git rebase -i HEAD~3`. You can then change the `pick` keywords in each line to `squash`. 
Once you save that you will be prompted to update your commit message.
As the bot mentioned above we use something called as [semantic commit messages](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines). It is essentially a guideline to format your commit messages. Again this makes your git history  neater and easier to go through.
So for this change you can have something like: `chore: change filename from xyz to abc`

You can google or ask here if you have any issues!

**Comment by rsarky** [comment]
Hey, you neednt close this PR. You can make the changes in the same one

**Comment by blogpranav** [comment]
ok i'll do it. thanks for the help

**Comment by blogpranav** [comment]
Can I just close this PR and create a new one with all the required changes? It's a bit confusing for me as I'm new to git.

**Comment by rsarky** [comment]
Sure whatever suits you

**Pull request closed without merging**
